### ISSUE TITLE
CUDA out of memory when sinkhorn_iterations == 100?

### ISSUE THREAD

**Issue by skylook** [magicleap/SuperGluePretrainedNetwork#51]
Hi, 
I am trying to write a simple code that run superglue model with fake input batch size == 4 (batch size < 4 seems to work well), how ever it crashes with CUDA out of memory error. Is there any thing wrong with it or I have to change the superglue.py code?
PS: Could SuperGlue be trained on one 2020 GPU card?

My code is here:

```python
import torch
import torch.nn as nn

import numpy as np

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# from common.utils.cuda import print_gpu_memory

# from config import GetConfig
# from opt import GetOpt

from models.superglue import SuperGlue

torch.set_grad_enabled(True)

torch.backends.cudnn.deterministic = False
torch.backends.cudnn.benchmark = False

import torch
from loguru import logger

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print('device = {}'.format(device))

def to_GB(memory):
    return round(memory/1024**3, 1)


def print_gpu_memory(name="", id=0):
    t = torch.cuda.get_device_properties(id).total_memory
    # c = torch.cuda.memory_reserved(id)
    a = torch.cuda.memory_allocated(id)
    # f = c-a  # free inside cache

    # print('Free GPU memory : {}/{}'.format(f, t))
    logger.info('{} GPU memory : {}/{} GB'.format(name, to_GB(a), to_GB(t)))


# import pynvml
# pynvml.nvmlInit()
# # GPU的id
# handle = pynvml.nvmlDeviceGetHandleByIndex(0)
# meminfo = pynvml.nvmlDeviceGetMemoryInfo(handle)
# print(meminfo.used)

batchsize = 8
keypoints = 1024
width = 2
height = 2

config = {
        'superpoint': {
                'nms_radius': 4.0,
                'keypoint_threshold': 0.005,
                'max_keypoints': keypoints
        },
        'superglue': {
                'weights': 'indoor',
                'sinkhorn_iterations': 100,
                'match_threshold': 0.2,
        }
}

print_gpu_memory(id=0)

superglue = SuperGlue(config.get('superglue', {}))

print_gpu_memory(name='init', id=0)

data = {'descriptors0':torch.rand((batchsize, 256, keypoints)).to(device),
        'descriptors1':torch.rand((batchsize, 256, keypoints)).to(device),
        'keypoints0':torch.rand((batchsize, keypoints, 2)).to(device),
        'keypoints1':torch.rand((batchsize, keypoints, 2)).to(device),
        'scores0':torch.rand((batchsize, keypoints)).to(device),
        'scores1':torch.rand((batchsize, keypoints)).to(device),
        'image0':np.random.rand(batchsize, 3, height, width),
        'image1': np.random.rand(batchsize, 3, height, width)}

print_gpu_memory(name='data', id=0)

superglue.to(device)

print_gpu_memory(name='model', id=0)

superglue(data)

print_gpu_memory(name='forward', id=0)


````
The runtime error message it here:
```bash
device = cuda
2020-12-29 18:25:19.262 | INFO     | __main__:print_gpu_memory:38 -  GPU memory : 0.0/10.8 GB
Loaded SuperGlue model ("indoor" weights)
2020-12-29 18:25:20.128 | INFO     | __main__:print_gpu_memory:38 - init GPU memory : 0.0/10.8 GB
2020-12-29 18:25:25.125 | INFO     | __main__:print_gpu_memory:38 - data GPU memory : 0.5/10.8 GB
2020-12-29 18:25:25.169 | INFO     | __main__:print_gpu_memory:38 - model GPU memory : 0.6/10.8 GB
Traceback (most recent call last):
  File "test_model_gputils.py", line 87, in <module>
    superglue(data)
  File "/home/liuxiao/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/Develop/SuperGluePretrainedNetwork/models/superglue.py", line 253, in forward
    desc0, desc1 = self.gnn(desc0, desc1)
  File "/home/liuxiao/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/Develop/SuperGluePretrainedNetwork/models/superglue.py", line 138, in forward
    delta0, delta1 = layer(desc0, src0), layer(desc1, src1)
  File "/home/liuxiao/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/Develop/SuperGluePretrainedNetwork/models/superglue.py", line 120, in forward
    message = self.attn(x, source, source)
  File "/home/liuxiao/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/Develop/SuperGluePretrainedNetwork/models/superglue.py", line 108, in forward
    x, _ = attention(query, key, value)
  File "/data/Develop/SuperGluePretrainedNetwork/models/superglue.py", line 89, in attention
    scores = torch.einsum('bdhn,bdhm->bhnm', query, key) / dim**.5
RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 10.76 GiB total capacity; 9.12 GiB already allocated; 359.12 MiB free; 9.55 GiB reserved in total by PyTorch)
INFO[0019] [Agent: A309085X9311734] Worker FAILED: user command error: exit code 1
```

Thx,
skylook

**Comment by skylook** [comment]
When I set 'sinkhorn_iterations': 100 the code run with OOM error, while sinkhorn_iterations = 20 and batch_size <= 4, the code works.

**Comment by Skydes** [comment]
The memory consumption depends on the batch size, number of keypoints, number of Sinkhorn iterations, and on whether autograd is enabled. Your code looks correct and I am not surprised that it throws an OOM around a batch size of 4. To decrease the memory consumption during training, you can use gradient checkpointing and reduce the number of Sinkhorn interations. This should allow larger batch sizes.

**Comment by skylook** [comment]
> The memory consumption depends on the batch size, number of keypoints, number of Sinkhorn iterations, and on whether autograd is enabled. Your code looks correct and I am not surprised that it throws an OOM around a batch size of 4. To decrease the memory consumption during training, you can use gradient checkpointing and reduce the number of Sinkhorn interations. This should allow larger batch sizes.

Dear @Skydes ,
Thanks for your response. So it means about 8 GPU cards are needed to reproduce the results (as in paper bs=64 and keypoints=400 is suggested in indoor dataset)?

**Comment by Skydes** [comment]
For both indoor and outdoor models, I think that we used 3-4 GPUs, but this number can be lowered using gradient checkpointing.

**Comment by skylook** [comment]
> For both indoor and outdoor models, I think that we used 3-4 GPUs, but this number can be lowered using gradient checkpointing.

Got it, thanks :+1:
